[profile.default]
src = "contracts"
script = 'contracts/script'
test = 'contracts/test'
out = "out"
libs = ["lib"]
evm_version = "cancun"
gas_reports = ["PointTokenVault"]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
fs_permissions = [{ access = "read", path = "./js-scripts/generateRedemptionRights/last-alpha-distribution.json" },
{ access = "read", path = "./js-scripts/generateRedemptionRights/out/merged-distribution.json" },
{ access = "read", path = "js-scripts/generateRedemptionRights/out/merged-distribution-03Dec24.json" },
{ access = "read", path = "js-scripts/generateRedemptionRights/out/merged-distribution-07Jan25.json" },
{ access = "read", path = "js-scripts/generateRedemptionRights/out/merged-distribution-06Feb25.json" },
{ access = "read", path = "js-scripts/generateRedemptionRights/out/merged-distribution-01Apr25.json" },
{ access = "read", path = "js-scripts/generateRedemptionRights/out/merged-distribution-29Apr25.json" },
{ access = "read", path = "./js-scripts/generateRedemptionRights/out/ptoken-snapshot-kpsats.json" },
{ access = "read", path = "js-scripts/etherFiS4Rewards/KingRewards.json" },
{ access = "read", path = "js-scripts/etherFiS4Rewards/KingRewards_3_5_25.json" },
{ access = "read", path = "./out/PointTokenVault.sol/PointTokenVault.json" }]
optimize = true
optimizer_runs = 100

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = {key = "${ETHERSCAN_API_KEY}"}

[fuzz]
runs = 256

[invariant]
depth = 20
fail_on_revert = true
dictionary_weight = 60

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
