[profile.default]
src = "contracts"
script = 'contracts/script'
test = 'contracts/test'
out = "out"
libs = ["lib"]
evm_version = "cancun"
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = {key = "${ETHERSCAN_API_KEY}"}

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
