[profile.default]
src = "contracts"
script = 'contracts/script'
test = 'contracts/test'
out = "contracts/out"
libs = ["lib"]
ffi = true
evm_version = "cancun"
gas_reports = ["PointTokenVault"]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = {key = "${ETHERSCAN_API_KEY}"}

[fuzz]
runs = 256

[invariant]
depth = 20
fail_on_revert = true
dictionary_weight = 60

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
